linters:
    Comment:
        enabled: false

    EmptyLineBetweenBlocks:
        ignore_single_line_blocks: false

    ImportPath:
        leading_underscore: false

    Indentation:
        width: 4

    LeadingZero:
        style: include_zero

    QualifyingElement:
        allow_element_with_attribute: true

    SingleLinePerProperty:
        allow_single_line_rule_sets: false

    UrlQuotes:
        enabled: false
